# ==== Base builder image ====
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json tsconfig.json
COPY src src

RUN npm run build

# ==== Production image ====
FROM node:20-alpine AS production
WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY database.sqlite database.sqlite

EXPOSE 9000

CMD ["node", "dist/index.js"]

